### ISSUE TITLE
Event Signup Limits

### ISSUE THREAD

**Issue by twiceineverymoment** [enforcer574/smashclub#105]
Allow officers to specify a signup limit on each event. If left blank, there will be no limit.

Once the signup limit is reached, the event will show as "Full" and not allow any more users to sign up.

**Comment by enforcer574** [comment]
Database change:
ALTER TABLE event_schedule ADD COLUMN event_signup_limit INT(11) NOT NULL DEFAULT -1

**Comment by enforcer574** [comment]
Test case:
- Create an event with a signup limit of 5
- After 5 members have signed up for the event, it should show as "full" on the Events tab
- Create an event and leave the signup limit empty
- Any number of members should be able to signup for this event
