### ISSUE TITLE
Double Elimination 20 player Automated Bracket Generation

### ISSUE THREAD

**Issue by PlsExplnTheJoke** [enforcer574/smashclub#114]
When testing Automated bracket generation (#80 ). A double elimination bracket of 20 players returns bracket builder error in Test. All other player combination, bracket builder finished successfully. 
![image](https://user-images.githubusercontent.com/40778624/42527860-d99109e4-8447-11e8-9d16-93b4d6319d0f.png)

**Comment by enforcer574** [comment]
Priority change to P2 due to workaround: Manual entry

**Comment by enforcer574** [comment]
Pending retest in v2.5.119

**Comment by enforcer574** [comment]
Retest passed
