### ISSUE TITLE
Empty Limit for Event Creation

### ISSUE THREAD

**Issue by PlsExplnTheJoke** [enforcer574/smashclub#115]
If an event is created with an empty sign up limit, it will not allow any members to sign up. (#105 )

**Comment by enforcer574** [comment]
Confirmed.
event_signup_limit is being set to 0 instead of -1 when the field is left blank.
Workaround: Provide a value for the signup limit, or type in -1 for no limit, and it works correctly.

**Comment by enforcer574** [comment]
Pending retest in v2.5.119

**Comment by enforcer574** [comment]
Retest passed
