### ISSUE TITLE
Limit size of "past events" list

### ISSUE THREAD

**Issue by twiceineverymoment** [enforcer574/smashclub#122]
Add a configuration setting for the maximum age of past events in days to display (default 30.)

Past events older than that number of days will not be shown on the page, but they remain in the database for record-keeping (required by the new hall of records updates.)

**Comment by enforcer574** [comment]
Test case:
- View the Events page
- Confirm that the past events section of the page only shows events up to the number of days specified by the site setting 'PastEventAgeLimit' (default 30 days)

**Comment by enforcer574** [comment]
Testing passed
