### ISSUE TITLE
Enhanced Guest Signups

### ISSUE THREAD

**Issue by twiceineverymoment** [enforcer574/smashclub#94]
This will provide extra functionality for the guest sign-up feature.

- Users signing up as guests will be required to provide both an email address and a phone number.
- Guests will receive email confirmation of their signup.
- Guests will be created as accounts with a user_type of 6. These accounts are "dummy" accounts with no password and no capability to log in. They do not appear on the Members page.
- Guests have no ranking. During tournaments, matches against guests will not affect rankings.
- The "Registration" page will be updated with the option to convert a guest account into a full account. Email and phone must be verified in order to do this.
- The guest account will be valid for one event, but stays in the system, meaning the gamertag will remain used. If the person wants to attend a second event, they must set up a full account.

**Comment by enforcer574** [comment]
User_type will be 0 for guest accounts.
This updated process will only take place for tournaments. For other types of event, the current guest signup process will remain in place.
